### ISSUE TITLE
Sublime Text 3 - Carriage Return markers show on format

### ISSUE THREAD

**Issue by elricstorm** [CraigWilliams/BeautifyRuby#41]
My line ending in SB3 are set to windows.  When I run CTRL+ALT+K the formatting works fine but shows a CR at the end of every line.  How do I get rid of the CR formatting mark showing up on every beautify_ruby command?

I have tried linux line endings as well and the same thing happens.

I am running windows 7, sublime text 3 and the latest BeautifyRuby gem.

**Comment by gowk** [comment]
Maybe It's a bug of Sublime Text 3.

**Comment by pioz** [comment]
I've same problem on OSX. Any update?
