### ISSUE TITLE
Interpreter settings not working

### ISSUE THREAD

**Issue by soupdiver** [CraigWilliams/BeautifyRuby#52]
Hey,
I just installed the plugin on Sublime 3 via the package manager.

```
which ruby                                                                                                          
/usr/local/opt/ruby/bin/ruby
```

Then I went to `preferences > package settings > beautify ruby > settings default` but I'm not able to edit this file.
So I added

``` javascript
{
  "ruby": "/usr/local/opt/ruby/bin/ruby"
}
```

to the user settings of the package but when I try to use it I still get "check your ruby interpreter settings"

What am I doing wrong?

**Comment by RONNCC** [comment]
This still doesn't work for me?

**Comment by nozpheratu** [comment]
@RONNCC Did you install the [https://github.com/threedaymonk/htmlbeautifier](htmlbeautifier) gem as mentioned in the readme?

**Comment by RONNCC** [comment]
Yup and I put my ruby path using where and I changed the requires to the
direct path of the htmlbeautifier as suggested above

**Comment by RossKinsella** [comment]
Tried everything in this post and no luck.

What might be worth noting is I only get the error on saving .html.erb files.

I'm running:
- OSX
- Sublime 3
- Installed from package manager
- RVM
- Ruby 2.12.

**Comment by RONNCC** [comment]
^ exact same. I only get the error on .html.erb files as well

**Comment by Corstiaan84** [comment]
@Josh-Kes his instructions worked for me. Thanks

**Comment by bobzhen** [comment]
@stujo Your solution works for me, thanks!!!

**Comment by prokizzle** [comment]
I was using chruby, and I had updated my system ruby to 2.1.5 using postmodern's ruby-install. The above solutions did not work, without a little finesse.

What finally worked for me (even after changing the beautifyruby sublime user settings ruby path to /Users/prokizzle/.rubies/ruby-2.1.5/bin/ruby) was running:

/usr/bin/gem install htmlbeautifier

Now everything is great.

**Comment by lizhangyuh** [comment]
What worked for me:
1.Add ruby path to beautifyruby sublime user settings
2.Install htmlbeautifie in global gemset:

```
rvm use (version)@global     
gem install htmlbeautifier
```

**Comment by krishnasrihari** [comment]
Thanks @lizhangyuh, it works for me.

**Comment by ronzalo** [comment]
with rbenv, this works for me
`rbenv which ruby`
`"ruby": "/Users/gonzalomoreno/.rbenv/versions/2.0.0-p353/bin/ruby"`

**Comment by ritaly** [comment]
Doesn't work. I still get the error on .html.erb files "Error: invalid output. Check your ruby interpreter settings"
* Sublime Text 3
* OSX (Sierra 10.12.6 )
* htmlbeautifier - installed
* `"ruby": "/opt/rubies/ruby-2.4.1/bin/ruby"`

I tired with installed from package manager & cloned (git clone git://github.com/CraigWilliams/BeautifyRuby.git)

**Comment by BKSpurgeon** [comment]
### If using rbenv see below:

#### 1. First navigate to your settings folder:

```terminal
On the sublime menu --> Preferences --> Package Settings --> BeautifyRuby --> Settings Default 
```

#### 2. Identify the path to ruby
Go to the terminal and type in: `which ruby` you should get a path like the following: 

```terminal
/home/your_username_goes_here_please_dont_blindly_cut_and_paste/.rbenv/shims/ruby
```

Ensure the above ruby path is correctly set in the BeautifyRuby configuration settings you opened up in step1:

```yaml
{
    // enter the path ruby below:
    "ruby" : "/home/your_username_goes_here_please_dont_blindly_cut_and_paste/.rbenv/shims/ruby",
    "file_patterns": ["\\.html\\.erb", "\\.rb", "\\.rake", "Rakefile", "Gemfile", "Vagrantfile"],
    "html_erb_patterns": ["\\.html\\.erb"],
    "run_on_save": true,
    "save_on_beautify": true
}

```
