### ISSUE TITLE
[Windows 7, x64] Invalid output. Check your interpreter settings

### ISSUE THREAD

**Issue by Javix** [CraigWilliams/BeautifyRuby#83]
I installed the package in SublimeText2 on Windws 7, 64 bits.
I also installed the htmlbeautifier gem (https://github.com/threedaymonk/htmlbeautifier), then modified User settings in ST2 as follows as it was suggested in your README file:
```
{
    // Would you prefer a tab or two spaces to represent a tab
    // The default is two spaces represented by 'space'
    // anything else will use one tab character
    "file_patterns": ["\\.html\\.erb", "\\.rb", "\\.rake", "Rakefile", "Gemfile"],
    "html_erb_patterns": ["\\.html\\.erb"],
    "run_on_save": false,
    "save_on_beautify": true,
    "ruby": "ruby"
}
```
When hitting `CTRL-ALT-k` I got the below error displayed in a popup:
```
Error: Invalid output. Check your interpreter settings
```
I have Ruby installed:
```
C:\Windows\system32>ruby -v
ruby 2.1.5p273 (2014-11-13 revision 48405) [x64-mingw32]
```
So the formatting does not work as needed. Any idea ? Thank you

**Comment by pranavpr** [comment]
Check this 

https://github.com/CraigWilliams/BeautifyRuby/issues/81

**Comment by Javix** [comment]
OK, thank you, I'll take a try.
