### ISSUE TITLE
Unexpected trailing characters

### ISSUE THREAD

**Issue by shaunstanislaus** [CraigWilliams/BeautifyRuby#97]
<img width="1172" alt="screen shot 2015-08-08 at 10 59 23" src="https://cloud.githubusercontent.com/assets/1703530/9148783/a987bb3c-3dbc-11e5-9a8d-3611dbdb4d4c.png">

it didn't happened before, what's wrong with my LINE : 1 ?

**Comment by shaunstanislaus** [comment]
can anyone reply me?

**Comment by shaunstanislaus** [comment]
why isn't anyone replying to this?

**Comment by zxqfox** [comment]
![image](https://cloud.githubusercontent.com/assets/677518/9431990/fe3083b2-4a23-11e5-992c-f5ef1f5161ae.png)

This file should be a valid JSON: http://www.json.org/

Try to put your file content here: http://jsonlint.com/ — I guess it will help you a lot.

**Comment by shaunstanislaus** [comment]
i pasted it in but it said valid, but its weird that i am getting that error. ):

**Comment by zxqfox** [comment]
@shaunstanislaus Can you make a screenshot?

**Comment by zxqfox** [comment]
That's what I see

![image](https://cloud.githubusercontent.com/assets/677518/9432121/b3261a4c-4a25-11e5-9413-bf353dfb4be8.png)

**Comment by shaunstanislaus** [comment]
I think I fixed it haha, I make it all into one bracket by adding comma after each line.

**Comment by zxqfox** [comment]
That's right. JSON is not YAML. ;-) Only 1 document (object in JSON terminology) allowed in a stream (or file).
